# Generated by Django 4.1.4 on 2022-12-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandasdemo', '0002_baka_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baka',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
